### ISSUE TITLE
RuntimeError: Given input size: (512x1x3). Calculated output size: (512x0x1). Output size is too small

### ISSUE THREAD

**Issue by ruanjiyang** [futscdav/strotss#4]
Dear Futscdav

I faced this error while using some style images.   could you please check? thanks!

Actually the images used be me are big enough.  >=1024.

The following is the detail logs.

Traceback (most recent call last):

  File "index-8023.py", line 169, in ai_photo
    run_strotss(
  File "C:\Qsync\ai\ai-tools\8023-pytorch-neural-style-transfer\strotss.py", line 451, in run_strotss
    result = strotss(pil_resize_long_edge_to(content_pil, args.resize_to),
  File "C:\Qsync\ai\ai-tools\8023-pytorch-neural-style-transfer\strotss.py", line 413, in strotss
    result = optimize(result, content, style, scale, content_weight=content_weight, lr=lr, extractor=extractor)
  File "C:\Qsync\ai\ai-tools\8023-pytorch-neural-style-transfer\strotss.py", line 355, in optimize
    feat_e = extractor.forward_samples_hypercolumn(style, samps=1000)  #ruanjiyang ， 寻找多少个features，缺省是1000，修改为500可以节约不少时间。效果稍微减弱。
  File "C:\Qsync\ai\ai-tools\8023-pytorch-neural-style-transfer\strotss.py", line 42, in forward_samples_hypercolumn
    feat = self.forward(X)
  File "C:\Qsync\ai\ai-tools\8023-pytorch-neural-style-transfer\strotss.py", line 38, in forward
    feat = self.forward_base(x)
  File "C:\Qsync\ai\ai-tools\8023-pytorch-neural-style-transfer\strotss.py", line 29, in forward_base
    x = self.vgg_layers[i](x)
  File "C:\Users\qruan\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "C:\Users\qruan\Anaconda3\lib\site-packages\torch\nn\modules\pooling.py", line 153, in forward
    return F.max_pool2d(input, self.kernel_size, self.stride,
  File "C:\Users\qruan\Anaconda3\lib\site-packages\torch\_jit_internal.py", line 267, in fn
    return if_false(*args, **kwargs)
  File "C:\Users\qruan\Anaconda3\lib\site-packages\torch\nn\functional.py", line 585, in _max_pool2d
    return torch.max_pool2d(
RuntimeError: Given input size: (512x1x3). Calculated output size: (512x0x1). Output size is too small

**Comment by ruanjiyang** [comment]
[
![9](https://user-images.githubusercontent.com/45660925/103724533-786be300-500f-11eb-8a01-589e126bd047.jpg)
](url)


for example, if I using this image as style image, it will raise such error.

**Comment by futscdav** [comment]
The long edge is resized to the maximum size, so the problem is that the image aspect ratio is too skewed. You can try either removing the resize or cutting a more square-ish AR image out of your style image and using that.

**Comment by ruanjiyang** [comment]
> The long edge is resized to the maximum size, so the problem is that the image aspect ratio is too skewed. You can try either removing the resize or cutting a more square-ish AR image out of your style image and using that.

Thanks very much for your comments. let me try as you suggestion and will let you know the result.

**Comment by ruanjiyang** [comment]
cutting the style image to square image and it works well. thanks again!
